# This is a config for E2B sandbox template.
# You can use template ID (dzhvx5bozysgfko1gt2a) or template name (goon-nextjs-test-3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("goon-nextjs-test-3") # Sync sandbox
# sandbox = await AsyncSandbox.create("goon-nextjs-test-3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('goon-nextjs-test-3')

team_id = "535a9f13-3382-44ef-8ce1-b9cbdb04f2e0"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "goon-nextjs-test-3"
template_id = "dzhvx5bozysgfko1gt2a"